#!/bin/bash
### =================================================================
##
##  Submits a trial script as a job to be run
##
### =================================================================

script=$1
tag=$2
name=${script%.*}

if [ -e $script ]; then
    echo "submitting script ${script} as a job"
else
    echo "script does not exist"
    exit 1
fi

qsub -d ./ -o ${name}_${tag}.out -v SCRIPT=${script} hello.sh

echo Output will be written to ${name}_${tag}.out