#!/bin/bash

### -----------------------------------------------------------------
##
##  Adds the path to the thesis directory to the list of directories
##
### -----------------------------------------------------------------

pathfile="pathsto"

pwd >> $pathfile
